package com.taskflowpro.reportservice.service;

import com.lowagie.text.*;
import com.lowagie.text.pdf.*;
import com.taskflowpro.reportservice.dto.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 * Service for generating PDF reports of tasks
 * Uses OpenPDF library to create formatted PDF documents
 */
@Service  // Spring will manage this as a singleton bean
public class TaskPdfService {
    
    private static final Logger logger = LoggerFactory.getLogger(TaskPdfService.class);
    
    // Font definitions for consistent styling
    private static final Font TITLE_FONT = new Font(Font.HELVETICA, 18, Font.BOLD, Color.BLACK);
    private static final Font HEADING_FONT = new Font(Font.HELVETICA, 12, Font.BOLD, Color.BLACK);
    private static final Font NORMAL_FONT = new Font(Font.HELVETICA, 10, Font.NORMAL, Color.BLACK);
    private static final Font SMALL_FONT = new Font(Font.HELVETICA, 9, Font.NORMAL, Color.DARK_GRAY);
    
    /**
     * Generates a PDF report from the provided task data
     * 
     * @param request The report request containing tasks and metadata
     * @return byte array containing the PDF file
     * @throws Exception if PDF generation fails
     */
    public byte[] generateTaskReportPdf(ReportRequest request) throws Exception {
        logger.info("Generating task PDF report with {} tasks", request.getTasks().size());
        
        // ByteArrayOutputStream holds the PDF in memory
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        
        // Create PDF document with A4 page size
        Document document = new Document(PageSize.A4, 36, 36, 54, 36);
        
        try {
            // PdfWriter connects the document to the output stream
            PdfWriter.getInstance(document, outputStream);
            
            // Open document for writing
            document.open();
            
            // Add title
            addTitle(document, request.getTitle());
            document.add(new Paragraph(" ")); // Spacer
            
            // Add metadata (generated by, date, etc.)
            addMetadata(document, request.getGeneratedBy(), request.getGeneratedAt());
            document.add(new Paragraph(" ")); // Spacer
            
            // Add filters section if filters exist
            if (request.getFilters() != null) {
                addFilters(document, request.getFilters());
                document.add(new Paragraph(" ")); // Spacer
            }
            
            // Add tasks table
            addTasksTable(document, request.getTasks());
            
            // Add footer with page numbers
            addFooter(document);
            
            logger.info("Task PDF report generated successfully");
            
        } finally {
            // Always close the document
            document.close();
        }
        
        return outputStream.toByteArray();
    }
    
    /**
     * Adds the main title to the document
     */
    private void addTitle(Document document, String title) throws DocumentException {
        Paragraph titleParagraph = new Paragraph(title, TITLE_FONT);
        titleParagraph.setAlignment(Element.ALIGN_CENTER);
        document.add(titleParagraph);
    }
    
    /**
     * Adds metadata information (who generated it, when)
     */
    private void addMetadata(Document document, String generatedBy, String generatedAt) throws DocumentException {
        Paragraph metadata = new Paragraph();
        metadata.add(new Chunk("Generated by: ", HEADING_FONT));
        metadata.add(new Chunk(generatedBy, NORMAL_FONT));
        metadata.add(Chunk.NEWLINE);
        metadata.add(new Chunk("Generated at: ", HEADING_FONT));
        metadata.add(new Chunk(formatDateTime(generatedAt), NORMAL_FONT));
        document.add(metadata);
    }
    
    /**
     * Adds filter information to show what criteria were used
     */
    private void addFilters(Document document, FilterDTO filters) throws DocumentException {
        Paragraph filterSection = new Paragraph();
        filterSection.add(new Chunk("Filters Applied:", HEADING_FONT));
        filterSection.add(Chunk.NEWLINE);
        
        if (filters.getDateFrom() != null && filters.getDateTo() != null) {
            filterSection.add(new Chunk("  Date Range: " + filters.getDateFrom() + " to " + filters.getDateTo(), NORMAL_FONT));
            filterSection.add(Chunk.NEWLINE);
        }
        
        if (filters.getPriority() != null && !filters.getPriority().isEmpty()) {
            filterSection.add(new Chunk("  Priority: " + String.join(", ", filters.getPriority()), NORMAL_FONT));
            filterSection.add(Chunk.NEWLINE);
        }
        
        if (filters.getStatus() != null && !filters.getStatus().isEmpty()) {
            filterSection.add(new Chunk("  Status: " + String.join(", ", filters.getStatus()), NORMAL_FONT));
            filterSection.add(Chunk.NEWLINE);
        }
        
        document.add(filterSection);
    }
    
    /**
     * Creates a table with all tasks and their details
     */
    private void addTasksTable(Document document, java.util.List<TaskDTO> tasks) throws DocumentException {
        // Create table with 6 columns
        PdfPTable table = new PdfPTable(6);
        table.setWidthPercentage(100);
        table.setSpacingBefore(10f);
        
        // Set column widths (relative proportions)
        table.setWidths(new float[]{3f, 1.5f, 1.5f, 1.5f, 1.5f, 3f});
        
        // Add header row
        addTableHeader(table);
        
        // Add data rows
        int rowNum = 0;
        for (TaskDTO task : tasks) {
            addTableRow(table, task, rowNum % 2 == 0);
            rowNum++;
        }
        
        document.add(table);
        
        // Add summary
        Paragraph summary = new Paragraph("\nTotal Tasks: " + tasks.size(), HEADING_FONT);
        document.add(summary);
    }
    
    /**
     * Adds header row to the table
     */
    private void addTableHeader(PdfPTable table) {
        String[] headers = {"Task Title", "Priority", "Status", "Created", "Due Date", "Assignees"};
        
        for (String header : headers) {
            PdfPCell cell = new PdfPCell(new Phrase(header, HEADING_FONT));
            cell.setBackgroundColor(new Color(70, 130, 180)); // Steel blue
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
            cell.setPadding(8);
            cell.setBorderColor(Color.WHITE);
            table.addCell(cell);
        }
    }
    
    /**
     * Adds a single task row to the table
     */
    private void addTableRow(PdfPTable table, TaskDTO task, boolean isEvenRow) {
        Color backgroundColor = isEvenRow ? Color.WHITE : new Color(245, 245, 245);
        
        // Task Title
        PdfPCell titleCell = createCell(task.getTitle(), backgroundColor);
        titleCell.setVerticalAlignment(Element.ALIGN_TOP);
        table.addCell(titleCell);
        
        // Priority
        PdfPCell priorityCell = createCell(capitalizeFirst(task.getPriority()), backgroundColor);
        priorityCell.setBackgroundColor(getPriorityColor(task.getPriority()));
        table.addCell(priorityCell);
        
        // Status
        PdfPCell statusCell = createCell(capitalizeFirst(task.getStatus()), backgroundColor);
        statusCell.setBackgroundColor(getStatusColor(task.getStatus()));
        table.addCell(statusCell);
        
        // Created Date
        table.addCell(createCell(formatDate(task.getCreatedAt()), backgroundColor));
        
        // Due Date
        table.addCell(createCell(formatDate(task.getDueDate()), backgroundColor));
        
        // Assignees
        String assigneeText = formatAssignees(task.getAssignees());
        table.addCell(createCell(assigneeText, backgroundColor));
    }
    
    /**
     * Helper method to create a table cell with consistent styling
     */
    private PdfPCell createCell(String text, Color backgroundColor) {
        PdfPCell cell = new PdfPCell(new Phrase(text, SMALL_FONT));
        cell.setBackgroundColor(backgroundColor);
        cell.setPadding(6);
        cell.setVerticalAlignment(Element.ALIGN_MIDDLE);
        return cell;
    }
    
    /**
     * Returns a color based on task priority
     */
    private Color getPriorityColor(String priority) {
        return switch (priority.toLowerCase()) {
            case "urgent" -> new Color(255, 200, 200); // Light red
            case "high" -> new Color(255, 220, 200);   // Light orange
            case "medium" -> new Color(255, 255, 200); // Light yellow
            case "low" -> new Color(200, 255, 200);    // Light green
            default -> Color.WHITE;
        };
    }
    
    /**
     * Returns a color based on task status
     */
    private Color getStatusColor(String status) {
        return switch (status.toLowerCase()) {
            case "completed" -> new Color(200, 255, 200);  // Light green
            case "in-progress" -> new Color(200, 220, 255); // Light blue
            case "pending" -> new Color(255, 255, 200);     // Light yellow
            default -> Color.WHITE;
        };
    }
    
    /**
     * Formats list of assignees into a readable string
     */
    private String formatAssignees(java.util.List<AssigneeDTO> assignees) {
        if (assignees == null || assignees.isEmpty()) {
            return "Unassigned";
        }
        
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < assignees.size(); i++) {
            AssigneeDTO assignee = assignees.get(i);
            sb.append(assignee.getName());
            sb.append(" (").append(assignee.getStatus());
            if (assignee.getProgress() != null) {
                sb.append(", ").append(assignee.getProgress()).append("%");
            }
            sb.append(")");
            
            if (i < assignees.size() - 1) {
                sb.append("\n");
            }
        }
        return sb.toString();
    }
    
    /**
     * Formats ISO date string to readable format
     */
    private String formatDate(String isoDate) {
        if (isoDate == null || isoDate.isEmpty()) {
            return "-";
        }
        try {
            // Parse ISO date and format as "Dec 09, 2025"
            return isoDate.substring(0, 10); // Just show YYYY-MM-DD for simplicity
        } catch (Exception e) {
            return isoDate;
        }
    }
    
    /**
     * Formats ISO datetime string to readable format
     */
    private String formatDateTime(String isoDateTime) {
        if (isoDateTime == null || isoDateTime.isEmpty()) {
            return "-";
        }
        try {
            return isoDateTime.replace("T", " ").substring(0, 19);
        } catch (Exception e) {
            return isoDateTime;
        }
    }
    
    /**
     * Capitalizes first letter of a string
     */
    private String capitalizeFirst(String text) {
        if (text == null || text.isEmpty()) {
            return text;
        }
        return text.substring(0, 1).toUpperCase() + text.substring(1);
    }
    
    /**
     * Adds a footer with generation info
     */
    private void addFooter(Document document) throws DocumentException {
        Paragraph footer = new Paragraph("\n\nTaskFlowPro - Task Management System", SMALL_FONT);
        footer.setAlignment(Element.ALIGN_CENTER);
        document.add(footer);
    }
}
