package com.taskflowpro.reportservice.service;

import com.taskflowpro.reportservice.dto.*;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;

/**
 * Service for generating Excel reports of tasks
 * Uses Apache POI library to create .xlsx files
 */
@Service
public class TaskExcelService {
    
    private static final Logger logger = LoggerFactory.getLogger(TaskExcelService.class);
    
    /**
     * Generates an Excel report from the provided task data
     * 
     * @param request The report request containing tasks and metadata
     * @return byte array containing the Excel file
     * @throws Exception if Excel generation fails
     */
    public byte[] generateTaskReportExcel(ReportRequest request) throws Exception {
        logger.info("Generating task Excel report with {} tasks", request.getTasks().size());
        
        // Create a new workbook (.xlsx format)
        try (Workbook workbook = new XSSFWorkbook()) {
            
            // Create a sheet named "Tasks Report"
            Sheet sheet = workbook.createSheet("Tasks Report");
            
            // Create cell styles
            CellStyle headerStyle = createHeaderStyle(workbook);
            CellStyle dataStyle = createDataStyle(workbook);
            CellStyle priorityHighStyle = createPriorityHighStyle(workbook);
            CellStyle statusCompletedStyle = createStatusCompletedStyle(workbook);
            
            int rowNum = 0;
            
            // Add title row
            Row titleRow = sheet.createRow(rowNum++);
            Cell titleCell = titleRow.createCell(0);
            titleCell.setCellValue(request.getTitle());
            titleCell.setCellStyle(createTitleStyle(workbook));
            
            // Add metadata rows
            rowNum = addMetadata(sheet, rowNum, request.getGeneratedBy(), request.getGeneratedAt());
            
            // Add filters if present
            if (request.getFilters() != null) {
                rowNum = addFilters(sheet, rowNum, request.getFilters());
            }
            
            // Add empty row
            rowNum++;
            
            // Add header row
            rowNum = addHeaderRow(sheet, rowNum, headerStyle);
            
            // Add data rows
            for (TaskDTO task : request.getTasks()) {
                rowNum = addTaskRow(sheet, rowNum, task, dataStyle, priorityHighStyle, statusCompletedStyle);
            }
            
            // Auto-size columns for better readability
            for (int i = 0; i < 8; i++) {
                sheet.autoSizeColumn(i);
                // Add a bit of extra width for comfort
                sheet.setColumnWidth(i, sheet.getColumnWidth(i) + 512);
            }
            
            // Write workbook to byte array
            ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
            workbook.write(outputStream);
            
            logger.info("Task Excel report generated successfully");
            return outputStream.toByteArray();
        }
    }
    
    /**
     * Adds metadata rows (generated by, date)
     */
    private int addMetadata(Sheet sheet, int rowNum, String generatedBy, String generatedAt) {
        Row generatedByRow = sheet.createRow(rowNum++);
        generatedByRow.createCell(0).setCellValue("Generated by:");
        generatedByRow.createCell(1).setCellValue(generatedBy);
        
        Row generatedAtRow = sheet.createRow(rowNum++);
        generatedAtRow.createCell(0).setCellValue("Generated at:");
        generatedAtRow.createCell(1).setCellValue(formatDateTime(generatedAt));
        
        return rowNum;
    }
    
    /**
     * Adds filter information rows
     */
    private int addFilters(Sheet sheet, int rowNum, FilterDTO filters) {
        Row filterHeaderRow = sheet.createRow(rowNum++);
        filterHeaderRow.createCell(0).setCellValue("Filters Applied:");
        
        if (filters.getDateFrom() != null && filters.getDateTo() != null) {
            Row dateRow = sheet.createRow(rowNum++);
            dateRow.createCell(0).setCellValue("  Date Range:");
            dateRow.createCell(1).setCellValue(filters.getDateFrom() + " to " + filters.getDateTo());
        }
        
        if (filters.getPriority() != null && !filters.getPriority().isEmpty()) {
            Row priorityRow = sheet.createRow(rowNum++);
            priorityRow.createCell(0).setCellValue("  Priority:");
            priorityRow.createCell(1).setCellValue(String.join(", ", filters.getPriority()));
        }
        
        if (filters.getStatus() != null && !filters.getStatus().isEmpty()) {
            Row statusRow = sheet.createRow(rowNum++);
            statusRow.createCell(0).setCellValue("  Status:");
            statusRow.createCell(1).setCellValue(String.join(", ", filters.getStatus()));
        }
        
        return rowNum;
    }
    
    /**
     * Adds the header row with column names
     */
    private int addHeaderRow(Sheet sheet, int rowNum, CellStyle headerStyle) {
        Row headerRow = sheet.createRow(rowNum++);
        
        String[] headers = {
            "Task Title", 
            "Description", 
            "Priority", 
            "Status", 
            "Created Date", 
            "Due Date", 
            "Assignee Names", 
            "Assignee Status"
        };
        
        for (int i = 0; i < headers.length; i++) {
            Cell cell = headerRow.createCell(i);
            cell.setCellValue(headers[i]);
            cell.setCellStyle(headerStyle);
        }
        
        return rowNum;
    }
    
    /**
     * Adds a single task row with all its data
     */
    private int addTaskRow(Sheet sheet, int rowNum, TaskDTO task, 
                          CellStyle dataStyle, CellStyle priorityHighStyle, 
                          CellStyle statusCompletedStyle) {
        Row row = sheet.createRow(rowNum++);
        
        // Task Title
        Cell titleCell = row.createCell(0);
        titleCell.setCellValue(task.getTitle());
        titleCell.setCellStyle(dataStyle);
        
        // Description
        Cell descCell = row.createCell(1);
        descCell.setCellValue(task.getDescription() != null ? task.getDescription() : "");
        descCell.setCellStyle(dataStyle);
        
        // Priority
        Cell priorityCell = row.createCell(2);
        priorityCell.setCellValue(capitalizeFirst(task.getPriority()));
        // Use special style for high/urgent priority
        if (task.getPriority().equalsIgnoreCase("high") || task.getPriority().equalsIgnoreCase("urgent")) {
            priorityCell.setCellStyle(priorityHighStyle);
        } else {
            priorityCell.setCellStyle(dataStyle);
        }
        
        // Status
        Cell statusCell = row.createCell(3);
        statusCell.setCellValue(capitalizeFirst(task.getStatus()));
        // Use special style for completed status
        if (task.getStatus().equalsIgnoreCase("completed")) {
            statusCell.setCellStyle(statusCompletedStyle);
        } else {
            statusCell.setCellStyle(dataStyle);
        }
        
        // Created Date
        Cell createdCell = row.createCell(4);
        createdCell.setCellValue(formatDate(task.getCreatedAt()));
        createdCell.setCellStyle(dataStyle);
        
        // Due Date
        Cell dueCell = row.createCell(5);
        dueCell.setCellValue(formatDate(task.getDueDate()));
        dueCell.setCellStyle(dataStyle);
        
        // Assignee Names
        Cell assigneeNamesCell = row.createCell(6);
        assigneeNamesCell.setCellValue(getAssigneeNames(task.getAssignees()));
        assigneeNamesCell.setCellStyle(dataStyle);
        
        // Assignee Status
        Cell assigneeStatusCell = row.createCell(7);
        assigneeStatusCell.setCellValue(getAssigneeStatus(task.getAssignees()));
        assigneeStatusCell.setCellStyle(dataStyle);
        
        return rowNum;
    }
    
    /**
     * Creates style for title row
     */
    private CellStyle createTitleStyle(Workbook workbook) {
        CellStyle style = workbook.createCellStyle();
        Font font = workbook.createFont();
        font.setBold(true);
        font.setFontHeightInPoints((short) 16);
        style.setFont(font);
        return style;
    }
    
    /**
     * Creates style for header row
     */
    private CellStyle createHeaderStyle(Workbook workbook) {
        CellStyle style = workbook.createCellStyle();
        
        // Font
        Font font = workbook.createFont();
        font.setBold(true);
        font.setFontHeightInPoints((short) 11);
        font.setColor(IndexedColors.WHITE.getIndex());
        style.setFont(font);
        
        // Background color (dark blue)
        style.setFillForegroundColor(IndexedColors.DARK_BLUE.getIndex());
        style.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        
        // Borders
        style.setBorderBottom(BorderStyle.THIN);
        style.setBorderTop(BorderStyle.THIN);
        style.setBorderLeft(BorderStyle.THIN);
        style.setBorderRight(BorderStyle.THIN);
        
        // Alignment
        style.setAlignment(HorizontalAlignment.CENTER);
        style.setVerticalAlignment(VerticalAlignment.CENTER);
        
        return style;
    }
    
    /**
     * Creates style for regular data cells
     */
    private CellStyle createDataStyle(Workbook workbook) {
        CellStyle style = workbook.createCellStyle();
        
        // Borders
        style.setBorderBottom(BorderStyle.THIN);
        style.setBorderTop(BorderStyle.THIN);
        style.setBorderLeft(BorderStyle.THIN);
        style.setBorderRight(BorderStyle.THIN);
        
        // Alignment
        style.setVerticalAlignment(VerticalAlignment.TOP);
        style.setWrapText(true); // Allow text wrapping
        
        return style;
    }
    
    /**
     * Creates style for high priority cells
     */
    private CellStyle createPriorityHighStyle(Workbook workbook) {
        CellStyle style = createDataStyle(workbook);
        
        // Light red background
        style.setFillForegroundColor(IndexedColors.CORAL.getIndex());
        style.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        
        Font font = workbook.createFont();
        font.setBold(true);
        style.setFont(font);
        
        return style;
    }
    
    /**
     * Creates style for completed status cells
     */
    private CellStyle createStatusCompletedStyle(Workbook workbook) {
        CellStyle style = createDataStyle(workbook);
        
        // Light green background
        style.setFillForegroundColor(IndexedColors.LIGHT_GREEN.getIndex());
        style.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        
        return style;
    }
    
    /**
     * Extracts assignee names into a comma-separated string
     */
    private String getAssigneeNames(java.util.List<AssigneeDTO> assignees) {
        if (assignees == null || assignees.isEmpty()) {
            return "Unassigned";
        }
        
        return assignees.stream()
            .map(AssigneeDTO::getName)
            .reduce((a, b) -> a + ", " + b)
            .orElse("Unassigned");
    }
    
    /**
     * Extracts assignee status and progress into a formatted string
     */
    private String getAssigneeStatus(java.util.List<AssigneeDTO> assignees) {
        if (assignees == null || assignees.isEmpty()) {
            return "-";
        }
        
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < assignees.size(); i++) {
            AssigneeDTO assignee = assignees.get(i);
            sb.append(assignee.getName()).append(": ")
              .append(capitalizeFirst(assignee.getStatus()));
            
            if (assignee.getProgress() != null) {
                sb.append(" (").append(assignee.getProgress()).append("%)");
            }
            
            if (i < assignees.size() - 1) {
                sb.append("; ");
            }
        }
        return sb.toString();
    }
    
    /**
     * Formats ISO date string
     */
    private String formatDate(String isoDate) {
        if (isoDate == null || isoDate.isEmpty()) {
            return "-";
        }
        try {
            return isoDate.substring(0, 10);
        } catch (Exception e) {
            return isoDate;
        }
    }
    
    /**
     * Formats ISO datetime string
     */
    private String formatDateTime(String isoDateTime) {
        if (isoDateTime == null || isoDateTime.isEmpty()) {
            return "-";
        }
        try {
            return isoDateTime.replace("T", " ").substring(0, 19);
        } catch (Exception e) {
            return isoDateTime;
        }
    }
    
    /**
     * Capitalizes first letter
     */
    private String capitalizeFirst(String text) {
        if (text == null || text.isEmpty()) {
            return text;
        }
        return text.substring(0, 1).toUpperCase() + text.substring(1);
    }
}
