import { motion } from 'framer-motion'
import DashboardLayout from '../../components/layout/DashboardLayout'
import { FiFileText, FiDownload, FiServer, FiCheck, FiCode, FiDatabase, FiCoffee } from 'react-icons/fi'
import { SiSpringboot, SiApache } from 'react-icons/si'

function ReportsPage() {
  return (
    <DashboardLayout>
      <div className="max-w-6xl mx-auto p-8 space-y-8">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-center"
        >
          <h1 className="text-4xl font-bold bg-gradient-to-r from-indigo-600 via-purple-600 to-pink-500 bg-clip-text text-transparent mb-4">
            📊 Java-Powered Report Generation
          </h1>
          <p className="text-gray-600 text-lg">
            Advanced PDF and Excel reports generated by Java microservice
          </p>
        </motion.div>

        {/* Java Integration Info Card */}
        <motion.div
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ delay: 0.1 }}
          className="bg-gradient-to-br from-orange-50 to-red-50 border-2 border-orange-200 rounded-2xl p-8"
        >
          <div className="flex items-center gap-4 mb-6">
            <div className="w-16 h-16 bg-gradient-to-br from-orange-500 to-red-500 rounded-xl flex items-center justify-center">
              <FiCoffee className="text-white text-3xl" />
            </div>
            <div>
              <h2 className="text-2xl font-bold text-gray-900">Java + Maven Microservice</h2>
              <p className="text-gray-600">Spring Boot 3.2.1 | Java 21 | Port 8085</p>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
            <div className="bg-white rounded-xl p-4 shadow-sm">
              <div className="flex items-center gap-3 mb-2">
                <SiSpringboot className="text-green-600 text-2xl" />
                <h3 className="font-semibold text-gray-900">Spring Boot</h3>
              </div>
              <p className="text-sm text-gray-600">RESTful API framework with embedded Tomcat server</p>
            </div>

            <div className="bg-white rounded-xl p-4 shadow-sm">
              <div className="flex items-center gap-3 mb-2">
                <FiFileText className="text-red-600 text-2xl" />
                <h3 className="font-semibold text-gray-900">OpenPDF</h3>
              </div>
              <p className="text-sm text-gray-600">Professional PDF generation with color coding and styling</p>
            </div>

            <div className="bg-white rounded-xl p-4 shadow-sm">
              <div className="flex items-center gap-3 mb-2">
                <SiApache className="text-purple-600 text-2xl" />
                <h3 className="font-semibold text-gray-900">Apache POI</h3>
              </div>
              <p className="text-sm text-gray-600">Excel (.xlsx) generation with formatting and styles</p>
            </div>
          </div>

          <div className="bg-white rounded-xl p-6">
            <h3 className="font-semibold text-gray-900 mb-4 flex items-center gap-2">
              <FiServer className="text-indigo-600" />
              Architecture Flow
            </h3>
            <div className="space-y-3">
              <div className="flex items-center gap-3 text-sm">
                <div className="w-8 h-8 rounded-full bg-blue-100 text-blue-600 flex items-center justify-center font-semibold">1</div>
                <span className="text-gray-700">React Frontend (Port 5173) → User clicks "Export PDF" or "Export Excel"</span>
              </div>
              <div className="flex items-center gap-3 text-sm">
                <div className="w-8 h-8 rounded-full bg-blue-100 text-blue-600 flex items-center justify-center font-semibold">2</div>
                <span className="text-gray-700">Node.js Backend (Port 5000) → Fetches tasks from MongoDB</span>
              </div>
              <div className="flex items-center gap-3 text-sm">
                <div className="w-8 h-8 rounded-full bg-blue-100 text-blue-600 flex items-center justify-center font-semibold">3</div>
                <span className="text-gray-700">Node transforms data → Sends HTTP POST to Java service</span>
              </div>
              <div className="flex items-center gap-3 text-sm">
                <div className="w-8 h-8 rounded-full bg-orange-100 text-orange-600 flex items-center justify-center font-semibold">4</div>
                <span className="text-gray-700">Java Service (Port 8085) → Generates PDF/Excel with OpenPDF/Apache POI</span>
              </div>
              <div className="flex items-center gap-3 text-sm">
                <div className="w-8 h-8 rounded-full bg-green-100 text-green-600 flex items-center justify-center font-semibold">5</div>
                <span className="text-gray-700">Binary stream returned → User downloads file</span>
              </div>
            </div>
          </div>
        </motion.div>

        {/* Feature Cards */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {/* PDF Reports */}
          <motion.div
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.2 }}
            className="bg-gradient-to-br from-red-50 to-pink-50 border border-red-200 rounded-2xl p-6"
          >
            <div className="flex items-center gap-3 mb-4">
              <div className="w-12 h-12 bg-gradient-to-br from-red-500 to-pink-500 rounded-lg flex items-center justify-center">
                <FiFileText className="text-white text-xl" />
              </div>
              <h3 className="text-xl font-bold text-gray-900">PDF Reports</h3>
            </div>
            <ul className="space-y-2 mb-4">
              {[
                'Professional document layout',
                'Color-coded task priorities',
                'Styled tables with headers',
                'Filter summary section',
                'Date formatting',
                'Assignee progress visualization'
              ].map((feature, idx) => (
                <li key={idx} className="flex items-center gap-2 text-sm text-gray-700">
                  <FiCheck className="text-green-600" />
                  {feature}
                </li>
              ))}
            </ul>
            <div className="text-xs text-gray-500 bg-white rounded-lg p-3">
              <strong>Library:</strong> OpenPDF 1.3.34 (open-source PDF generation)
            </div>
          </motion.div>

          {/* Excel Reports */}
          <motion.div
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.3 }}
            className="bg-gradient-to-br from-green-50 to-emerald-50 border border-green-200 rounded-2xl p-6"
          >
            <div className="flex items-center gap-3 mb-4">
              <div className="w-12 h-12 bg-gradient-to-br from-green-500 to-emerald-500 rounded-lg flex items-center justify-center">
                <FiDownload className="text-white text-xl" />
              </div>
              <h3 className="text-xl font-bold text-gray-900">Excel Reports</h3>
            </div>
            <ul className="space-y-2 mb-4">
              {[
                'OOXML format (.xlsx)',
                'Styled header rows',
                'Auto-sized columns',
                'Conditional cell formatting',
                'Color highlights',
                'Multiple data columns (8 total)'
              ].map((feature, idx) => (
                <li key={idx} className="flex items-center gap-2 text-sm text-gray-700">
                  <FiCheck className="text-green-600" />
                  {feature}
                </li>
              ))}
            </ul>
            <div className="text-xs text-gray-500 bg-white rounded-lg p-3">
              <strong>Library:</strong> Apache POI 5.2.5 (Microsoft Office file generation)
            </div>
          </motion.div>
        </div>

        {/* Technologies Used */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.4 }}
          className="bg-gray-50 border border-gray-200 rounded-2xl p-6"
        >
          <h3 className="text-xl font-bold text-gray-900 mb-4 flex items-center gap-2">
            <FiCode />
            Java Technologies Demonstrated
          </h3>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            {[
              { name: 'Java 21 LTS', desc: 'Latest LTS version' },
              { name: 'Maven 3.9.11', desc: 'Build & dependencies' },
              { name: 'Spring Boot', desc: 'Microservice framework' },
              { name: 'Spring Web', desc: 'REST API creation' },
              { name: 'OpenPDF', desc: 'PDF generation' },
              { name: 'Apache POI', desc: 'Excel generation' },
              { name: 'Lombok', desc: 'Boilerplate reduction' },
              { name: 'Jakarta', desc: 'Request validation' }
            ].map((tech, idx) => (
              <div key={idx} className="bg-white rounded-lg p-3 text-center">
                <div className="font-semibold text-gray-900 text-sm">{tech.name}</div>
                <div className="text-xs text-gray-500 mt-1">{tech.desc}</div>
              </div>
            ))}
          </div>
        </motion.div>

        {/* Where to Use */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.5 }}
          className="bg-gradient-to-br from-indigo-50 to-purple-50 border-2 border-indigo-200 rounded-2xl p-8 text-center"
        >
          <h3 className="text-2xl font-bold text-gray-900 mb-4">📍 Where to Use This Feature</h3>
          <div className="space-y-3 text-left max-w-2xl mx-auto">
            <div className="bg-white rounded-lg p-4 shadow-sm">
              <div className="flex items-start gap-3">
                <div className="w-8 h-8 rounded-full bg-indigo-100 text-indigo-600 flex items-center justify-center flex-shrink-0 mt-1">
                  1
                </div>
                <div>
                  <h4 className="font-semibold text-gray-900 mb-1">Admin Dashboard</h4>
                  <p className="text-sm text-gray-600">Navigate to <strong>Admin Dashboard</strong> → Look for <strong>Export PDF</strong> and <strong>Export Excel</strong> buttons at the top-right corner</p>
                </div>
              </div>
            </div>
            <div className="bg-white rounded-lg p-4 shadow-sm">
              <div className="flex items-start gap-3">
                <div className="w-8 h-8 rounded-full bg-indigo-100 text-indigo-600 flex items-center justify-center flex-shrink-0 mt-1">
                  2
                </div>
                <div>
                  <h4 className="font-semibold text-gray-900 mb-1">All Tasks Page</h4>
                  <p className="text-sm text-gray-600">Go to <strong>All Tasks</strong> → Use the <strong>PDF</strong> and <strong>Excel</strong> export buttons (next to Create Task button)</p>
                </div>
              </div>
            </div>
            <div className="bg-white rounded-lg p-4 shadow-sm">
              <div className="flex items-start gap-3">
                <div className="w-8 h-8 rounded-full bg-indigo-100 text-indigo-600 flex items-center justify-center flex-shrink-0 mt-1">
                  ✓
                </div>
                <div>
                  <h4 className="font-semibold text-gray-900 mb-1">Filter & Export</h4>
                  <p className="text-sm text-gray-600">Apply filters (status, priority) on All Tasks page, then export to get filtered reports</p>
                </div>
              </div>
            </div>
          </div>
        </motion.div>

        {/* Status Indicator */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.6 }}
          className="text-center"
        >
          <div className="inline-flex items-center gap-2 px-6 py-3 bg-green-50 border border-green-200 rounded-full text-green-700 font-medium">
            <div className="w-2 h-2 rounded-full bg-green-500 animate-pulse"></div>
            Java Microservice Running on http://localhost:8085
          </div>
        </motion.div>
      </div>
    </DashboardLayout>
  )
}

export default ReportsPage
